### ISSUE TITLE
TimeoutError: [Errno 110] Connection timed out

### ISSUE THREAD

**Issue by boubaca** [sunfounder/picar-4wd#14]
pi@raspberrypi:~ $ picar-4wd test motor
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/picar_4wd-0.0.1-py3.7.egg/picar_4wd/i2c.py", line 17, in wrapper
    return func(*args, **kw)
  File "/usr/local/lib/python3.7/dist-packages/picar_4wd-0.0.1-py3.7.egg/picar_4wd/i2c.py", line 37, in _i2c_write_word_data
    return self._smbus.write_word_data(addr, reg, data)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/picar-4wd", line 11, in <module>
    load_entry_point('picar-4wd==0.0.1', 'console_scripts', 'picar-4wd')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.7/dist-packages/picar_4wd-0.0.1-py3.7.egg/picar_4wd/__init__.py", line 24, in <module>
    left_front = Motor(PWM("P13"), Pin("D4"), is_reversed=left_front_reverse) # motor 1
  File "/usr/local/lib/python3.7/dist-packages/picar_4wd-0.0.1-py3.7.egg/picar_4wd/pwm.py", line 35, in __init__
    self.freq(50)
  File "/usr/local/lib/python3.7/dist-packages/picar_4wd-0.0.1-py3.7.egg/picar_4wd/pwm.py", line 67, in freq
    self.prescaler(psc)
  File "/usr/local/lib/python3.7/dist-packages/picar_4wd-0.0.1-py3.7.egg/picar_4wd/pwm.py", line 77, in prescaler
    self.i2c_write(reg, self._prescaler)
  File "/usr/local/lib/python3.7/dist-packages/picar_4wd-0.0.1-py3.7.egg/picar_4wd/pwm.py", line 41, in i2c_write
    self.send([reg, value_h, value_l], self.ADDR)
  File "/usr/local/lib/python3.7/dist-packages/picar_4wd-0.0.1-py3.7.egg/picar_4wd/i2c.py", line 104, in send
    self._i2c_write_word_data(addr, reg, data)
  File "/usr/local/lib/python3.7/dist-packages/picar_4wd-0.0.1-py3.7.egg/picar_4wd/i2c.py", line 21, in wrapper
    return func(*args, **kw)
  File "/usr/local/lib/python3.7/dist-packages/picar_4wd-0.0.1-py3.7.egg/picar_4wd/i2c.py", line 37, in _i2c_write_word_data
    return self._smbus.write_word_data(addr, reg, data)
TimeoutError: [Errno 110] Connection timed out
pi@raspberrypi:~ $

**Comment by boubaca** [comment]
divice was bad , new one got shipped
